# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zande/Documents/VSCODE/SchoolStuff/ece153a/Labs/HardwareSetup/lab2b/lab2b.srcs/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6.xci
# IP: The module: 'system_axi_gpio_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zande/Documents/VSCODE/SchoolStuff/ece153a/Labs/HardwareSetup/lab2b/lab2b.srcs/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zande/Documents/VSCODE/SchoolStuff/ece153a/Labs/HardwareSetup/lab2b/lab2b.srcs/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zande/Documents/VSCODE/SchoolStuff/ece153a/Labs/HardwareSetup/lab2b/lab2b.srcs/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/zande/Documents/VSCODE/SchoolStuff/ece153a/Labs/HardwareSetup/lab2b/lab2b.srcs/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6.xci
# IP: The module: 'system_axi_gpio_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zande/Documents/VSCODE/SchoolStuff/ece153a/Labs/HardwareSetup/lab2b/lab2b.srcs/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zande/Documents/VSCODE/SchoolStuff/ece153a/Labs/HardwareSetup/lab2b/lab2b.srcs/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zande/Documents/VSCODE/SchoolStuff/ece153a/Labs/HardwareSetup/lab2b/lab2b.srcs/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
