# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zande/Documents/VSCODE/School Stuff/ece153a/HardwareSetup/lab2a/lab2a.srcs/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5.xci
# IP: The module: 'system_axi_gpio_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zande/Documents/VSCODE/School Stuff/ece153a/HardwareSetup/lab2a/lab2a.srcs/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zande/Documents/VSCODE/School Stuff/ece153a/HardwareSetup/lab2a/lab2a.srcs/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zande/Documents/VSCODE/School Stuff/ece153a/HardwareSetup/lab2a/lab2a.srcs/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/zande/Documents/VSCODE/School Stuff/ece153a/HardwareSetup/lab2a/lab2a.srcs/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5.xci
# IP: The module: 'system_axi_gpio_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zande/Documents/VSCODE/School Stuff/ece153a/HardwareSetup/lab2a/lab2a.srcs/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zande/Documents/VSCODE/School Stuff/ece153a/HardwareSetup/lab2a/lab2a.srcs/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zande/Documents/VSCODE/School Stuff/ece153a/HardwareSetup/lab2a/lab2a.srcs/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
